version: '3.0'
services:
  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
      - 192.168.0.155:3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    build: ./server/api
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
    volumes:
      - ./server/api:/app
      - /app/node_modules

  database:
    build: ./server/database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  proxy:
    build: ./server/proxy
    restart: always
    ports:
      - 80:80